server:
  port: 8081
spring:
  application:
    name: spring-boot-learning
  datasource:
    url: jdbc:mysql://localhost:3306/slyza_teams
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
